Aminity.create!([
	{ description: '8 Japanese Inspired Suites' },
	{ description: 'Outdoor Jacuzzi' },
	{ description: 'Non-chlorinated Swimming Pool' },
	{ description: 'Garden & Koi Pond' },
	{ description: 'Dinning Area' },
	{ description: 'Pavilion' },
	{ description: 'Indoor Playroom' },
	{ description: 'A/C' },
	{ description: 'TV' },
	{ description: 'WiFi' },
	{ description: 'Safe' },
	{ description: 'Minibar' },
	{ description: 'Shower' },
	{ description: 'Telephone' },
	{ description: 'Bath' },
	{ description: 'Kitchen' },
])