RoomAminity.create!([
	{ room_id: 1, aminity_id: 8 },
	{ room_id: 1, aminity_id: 9 },
	{ room_id: 1, aminity_id: 10 },
	{ room_id: 1, aminity_id: 11 },
	{ room_id: 1, aminity_id: 12 },
	{ room_id: 1, aminity_id: 13 },
	{ room_id: 1, aminity_id: 14 },
	{ room_id: 1, aminity_id: 15 },
	{ room_id: 1, aminity_id: 16 },

	{ room_id: 2, aminity_id: 8 },
	{ room_id: 2, aminity_id: 9 },
	{ room_id: 2, aminity_id: 10 },
	{ room_id: 2, aminity_id: 11 },
	{ room_id: 2, aminity_id: 12 },
	{ room_id: 2, aminity_id: 13 },
	{ room_id: 2, aminity_id: 14 },
	{ room_id: 2, aminity_id: 15 },
	{ room_id: 2, aminity_id: 16 },

	{ room_id: 3, aminity_id: 8 },
	{ room_id: 3, aminity_id: 9 },
	{ room_id: 3, aminity_id: 10 },
	{ room_id: 3, aminity_id: 11 },
	{ room_id: 3, aminity_id: 13 },
	{ room_id: 3, aminity_id: 14 },
	{ room_id: 3, aminity_id: 15 },
	{ room_id: 3, aminity_id: 16 },

	{ room_id: 4, aminity_id: 8 },
	{ room_id: 4, aminity_id: 9 },
	{ room_id: 4, aminity_id: 10 },
	{ room_id: 4, aminity_id: 11 },
	{ room_id: 4, aminity_id: 13 },
	{ room_id: 4, aminity_id: 14 },
	{ room_id: 4, aminity_id: 15 },
	{ room_id: 4, aminity_id: 16 },

	{ room_id: 5, aminity_id: 8 },
	{ room_id: 5, aminity_id: 9 },
	{ room_id: 5, aminity_id: 10 },
	{ room_id: 5, aminity_id: 11 },
	{ room_id: 5, aminity_id: 12 },
	{ room_id: 5, aminity_id: 13 },
	{ room_id: 5, aminity_id: 14 },
	{ room_id: 5, aminity_id: 15 },
	{ room_id: 5, aminity_id: 16 },

	{ room_id: 6, aminity_id: 8 },
	{ room_id: 6, aminity_id: 9 },
	{ room_id: 6, aminity_id: 10 },
	{ room_id: 6, aminity_id: 11 },
	{ room_id: 6, aminity_id: 12 },
	{ room_id: 6, aminity_id: 13 },
	{ room_id: 6, aminity_id: 14 },
	{ room_id: 6, aminity_id: 15 },
	{ room_id: 6, aminity_id: 16 },
])